import {
  Activity,
  Eye,
  Shield,
  Users,
  Globe,
  Cpu,
  Database,
  Zap,
  BarChart2,
  Target,
  Clock,
  TrendingUp,
  Award,
  Layers,
  GitBranch,
  Code2,
  HeartPulse,
  BrainCircuit,
  Stethoscope,
  ScanEye,
  Crosshair,
  Binary,
  Network,
  FlaskConical,
  Scan,
  Palette,
  Image,
  TestTube2,
  Pulse,
  MessageSquare,
  Bot,
  Server,
  CookingPot,
  Utensils,
  ListRestart,
  Smartphone,
  Video,
  Volume2,
  Mic,
  MonitorPlay,
  FileText
} from "lucide-react";

export const projects = [
  {
    id: 1,
    title: "Neon-Nexus",
    subtitle: "Real-time Auction Platform",
    description: "A revolutionary real-time auction platform powered by AI, featuring live bidding, intelligent product recommendations, and seamless payment integration.",
    youtubeId: "zuuFVVFkMno",
    videoUrl: "https://img.youtube.com/vi/zuuFVVFkMno/maxresdefault.jpg",
    liveUrl: "https://neon-nexus-demo.vercel.app",
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/Neonlatest",
    startDate: "Jan 2024",
    endDate: "Present",
    status: "Live",
    videoAvailable: true,
    technologies: ["Next.js 15", "Supabase", "WebSockets", "Stripe", "Google Vision API", "Tailwind CSS"],
    features: [
      { icon: Activity, text: "Real-time bidding", color: "text-cyan-400" },
      { icon: Eye, text: "AI product analysis", color: "text-purple-400" },
      { icon: Shield, text: "Secure payments", color: "text-green-400" },
      { icon: Users, text: "1000+ concurrent users", color: "text-yellow-400" },
    ],
    metrics: {
      users: "1000+",
      uptime: "99.9%",
      performance: 98,
      security: 95,
    },
    gradient: "from-cyan-500 to-purple-600",
  },
  {
    id: 14,
    title: "RESTify",
    subtitle: "Windows API Testing App (like Postman)",
    description: "A Windows desktop application for testing REST APIs, similar to Postman. RESTify allows users to send requests to online APIs (like Fake JSON Testing API) and local APIs, view all requests and responses, and manage API collections. Built with Electron and Electron Store for persistent storage.",
    youtubeId: "hp4PeJmRnj0",
    videoAvailable: true,
    videoUrl: "https://img.youtube.com/vi/hp4PeJmRnj0/maxresdefault.jpg",
    technologies: ["Electron", "Electron Store", "JavaScript", "HTML5", "CSS3", "Node.js"],
    features: [
      { icon: MonitorPlay, text: "Windows Desktop App", color: "text-cyan-400" },
      { icon: Server, text: "Test Online & Local APIs", color: "text-purple-400" },
      { icon: Database, text: "Request/Response History", color: "text-green-400" },
      { icon: Code2, text: "API Collection Management", color: "text-yellow-400" },
      { icon: Shield, text: "Persistent Storage", color: "text-red-400" },
      { icon: Globe, text: "Fake JSON API Support", color: "text-blue-400" }
    ],
    metrics: {
      users: "Developers",
      uptime: "100%",
      performance: 95,
      security: 95,
    },
    gradient: "from-gray-700 to-blue-700",
    skills: [
      "Electron",
      "API Testing",
      "Electron Store",
      "JavaScript",
      "Desktop App Development",
      "Request/Response Management",
      "API Collections"
    ],
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/restify",
    liveUrl: "",
    startDate: "Jul 2025",
    endDate: "Jul 2025",
    status: "Live"
  },
  {
    id: 2,
    title: "Image-Gen",
    subtitle: "AI Image Generator App",
    description: "An AI Image Generator app using Next.js that leverages advanced technologies to bring AI-generated images to life.",
    youtubeId: "YRrcWkOyxPs",
    videoUrl: "https://img.youtube.com/vi/YRrcWkOyxPs/maxresdefault.jpg",
    liveUrl: "https://image-gen-demo.vercel.app",
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/Image-gen",
    startDate: "7/dec/2024",
    endDate: "12/dec/2024",
    status: "Live",
    videoAvailable: true,
    technologies: ["Next.js", "Tailwind CSS", "Supabase", "Cloudinary", "Hono", "Shadcn", "Turbopack"],
    features: [
      { icon: Globe, text: "Dynamic Header", color: "text-red-400" },
      { icon: Cpu, text: "Customizable Footer", color: "text-blue-400" },
      { icon: Database, text: "AI Image Generation", color: "text-green-400" },
      { icon: Users, text: "Theme Selection", color: "text-yellow-400" },
      { icon: Shield, text: "Dark Mode Toggle", color: "text-purple-400" },
      { icon: Eye, text: "Image Upload and Storage", color: "text-cyan-400" },
      { icon: Zap, text: "Supabase Indexing", color: "text-orange-400" },
      { icon: Activity, text: "Fallback Mechanism", color: "text-pink-400" },
    ],
    metrics: {
      users: "500+",
      uptime: "99.5%",
      performance: 92,
      security: 90,
    },
    gradient: "from-purple-500 to-pink-600",
  },
  {
    id: 3,
    title: "Multiple PDF Chat App",
    subtitle: "Interactive PDF Conversational Interface",
    description: "A Streamlit app that allows users to chat with multiple PDFs using LangChain and Google Generative AI (Gemini).",
    youtubeId: "HCHF8BneqV8",
    videoUrl: "https://img.youtube.com/vi/HCHF8BneqV8/maxresdefault.jpg",
    liveUrl: "https://pdf-chat-app-demo.vercel.app",
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/-Chat-with-multiple-pdf",
    startDate: "25/Nov/2024",
    endDate: "25/Nov/2024",
    status: "Live",
    videoAvailable: true,
    technologies: ["Streamlit", "PyPDF2", "LangChain", "Google Generative AI", "FAISS", "dotenv"],
    features: [
      { icon: Database, text: "Multiple PDF Support", color: "text-green-400" },
      { icon: Globe, text: "Smart Interaction", color: "text-red-400" },
      { icon: Zap, text: "Vector Search with FAISS", color: "text-orange-400" },
      { icon: Shield, text: "Generative AI Integration", color: "text-purple-400" },
    ],
    metrics: {
      users: "1500+",
      uptime: "99.7%",
      performance: 95,
      security: 93,
    },
    gradient: "from-blue-500 to-green-600",
  },
  {
    id: 4,
    title: "Cricket Runs And Win Predictor for Psl",
    subtitle: "Runs & Winner Prediction System trained on 278 Psl Matches",
    description: "Machine learning system to predict second-innings runs and match winners using historical cricket data, developed in association with NUST.",
    youtubeId: "FW8QQd1dQ5w",
    videoUrl: "https://img.youtube.com/vi/FW8QQd1dQ5w/maxresdefault.jpg",
    startDate: "Jan 2025",
    endDate: "Jan 2025",
    status: "Demo",
    videoAvailable: true,
    technologies: ["Python", "Pandas", "XGBoost", "Scikit-learn", "PyYAML", "GridSearchCV", "KFold"],
    features: [
      { icon: BarChart2, text: "Dual Prediction System", color: "text-cyan-400" },
      { icon: Target, text: "Run Rate Analysis", color: "text-purple-400" },
      { icon: Clock, text: "Balls Remaining Calculation", color: "text-green-400" },
      { icon: TrendingUp, text: "Feature Engineering", color: "text-yellow-400" },
      { icon: Award, text: "Model Optimization", color: "text-red-400" },
      { icon: Layers, text: "Pipeline Creation", color: "text-blue-400" },
      { icon: GitBranch, text: "Cross-Validation", color: "text-orange-400" },
      { icon: Code2, text: "Data Preprocessing", color: "text-pink-400" },
    ],
    metrics: {
      users: "NUST Research",
      uptime: "100%",
      performance: 96,
      security: 98,
    },
    gradient: "from-orange-500 to-red-600",
    associatedWith: "National University of Sciences and Technology (NUST)",
    keyAchievements: [
      "Accurate run predictions (e.g., predicted 180 total runs when 100 needed in 5 overs)",
      "Winner classification with high accuracy",
      "Feature engineering for cricket-specific metrics",
      "Hyperparameter tuning with GridSearchCV"
    ],
    skills: [
      "Machine Learning",
      "Standardization and Normalization",
      "Regression Analysis",
      "One-Hot Encoding",
      "Data Cleaning",
      "Feature Engineering",
      "Hyperparameter Tuning",
      "Pipeline Creation",
      "Classification Models"
    ]
  },
  {
    id: 11,
    title: "AI Voice Clone",
    subtitle: "Text-to-Speech with Bark",
    description: "A text-to-speech application using Suno's Bark model to generate realistic voice outputs from text inputs with Python and Transformers.",
    youtubeId: "gV8XbJXo6iE",
    videoUrl: "https://img.youtube.com/vi/gV8XbJXo6iE/maxresdefault.jpg",
    startDate: "Jun 2024",
    endDate: "Jun 2024",
    status: "Demo",
    videoAvailable: true,
    technologies: ["Python", "Transformers", "Torch", "Bark", "IPython", "Torchaudio"],
    features: [
      { icon: Volume2, text: "Text-to-Speech Conversion", color: "text-cyan-400" },
      { icon: Mic, text: "Natural Voice Generation", color: "text-purple-400" },
      { icon: Cpu, text: "Local Processing", color: "text-green-400" },
      { icon: Code2, text: "Open-Source Model", color: "text-yellow-400" },
      { icon: Shield, text: "Privacy Focused", color: "text-red-400" },
      { icon: Activity, text: "Real-time Playback", color: "text-blue-400" }
    ],
    metrics: {
      users: "Developers",
      uptime: "100%",
      performance: 90,
      security: 95,
    },
    gradient: "from-blue-500 to-cyan-600",
    skills: [
      "Python",
      "Transformers",
      "Torch",
      "Text-to-Speech",
      "AI Voice Generation",
      "Audio Processing",
      "IPython Integration"
    ],
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/ai-voice-clone",
    keyAchievements: [
      "Implemented Bark text-to-speech model",
      "Real-time audio generation and playback",
      "Local processing for privacy",
      "Easy integration with Jupyter notebooks"
    ]
  },
  {
    id: 9,
    title: "Video-Gen",
    subtitle: "AI Video Generation with Stable Diffusion",
    description: "A Python application that generates videos from text prompts using the Stable Diffusion model, optimized for GPU performance with frame processing and video export capabilities.",
    youtubeId: "V3dTMWnvsng",
    videoUrl: "https://img.youtube.com/vi/V3dTMWnvsng/maxresdefault.jpg",
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/Video-gen",
    startDate: "Jun 2024",
    endDate: "Jun 2024",
    status: "Demo",
    videoAvailable: true,
    technologies: ["Python", "Diffusers", "Transformers", "Torch", "ModelScope", "NumPy"],
    features: [
      { icon: Video, text: "Text-to-Video Generation", color: "text-cyan-400" },
      { icon: Cpu, text: "GPU Optimization", color: "text-purple-400" },
      { icon: Database, text: "Frame Processing", color: "text-green-400" },
      { icon: Shield, text: "Memory Efficient", color: "text-yellow-400" },
      { icon: Code2, text: "ModelScope Integration", color: "text-red-400" },
      { icon: Activity, text: "Real-time Debugging", color: "text-blue-400" }
    ],
    metrics: {
      users: "AI Researchers",
      uptime: "100%",
      performance: 90,
      security: 85,
    },
    gradient: "from-emerald-500 to-teal-600",
    skills: [
      "AI Video Generation",
      "Stable Diffusion",
      "GPU Optimization",
      "Python",
      "Frame Processing",
      "ModelScope",
      "Debugging",
      "Video Export"
    ],
    keyAchievements: [
      "Implemented text-to-video generation pipeline",
      "Optimized for GPU memory efficiency",
      "Developed frame processing and debugging tools",
      "Integrated with ModelScope's text-to-video model"
    ]
  },
  {
    id: 8,
    title: "StabilityAI Stable Diffusion 3.5 Large",
    subtitle: "AI Image Generation App",
    description: "A Gradio-based AI image generator using StabilityAI's Stable Diffusion 3.5 Large model, deployed on Hugging Face Spaces.",
    startDate: "about 2 months ago",
    endDate: "about 2 months ago",
    status: "Live",
    videoAvailable: false,
    videoUrl: "/placeholder.svg?height=400&width=600",
    technologies: ["Gradio", "Python", "Hugging Face Spaces", "Stable Diffusion 3.5", "Fal.ai API"],
    features: [
      { icon: Image, text: "AI Image Generation", color: "text-cyan-400" },
      { icon: Palette, text: "Prompt Customization", color: "text-purple-400" },
      { icon: Shield, text: "Secure API Integration", color: "text-green-400" },
      { icon: Globe, text: "Hugging Face Deployment", color: "text-yellow-400" },
      { icon: Cpu, text: "Fast SDXL Model", color: "text-red-400" },
      { icon: Users, text: "User-friendly Interface", color: "text-blue-400" }
    ],
    metrics: {
      users: "Hugging Face Community",
      uptime: "99.8%",
      performance: 94,
      security: 90,
    },
    gradient: "from-violet-500 to-indigo-600",
    liveUrl: "https://huggingface.co/spaces/DaniDaniels/stabilityai-stable-diffusion-3.5-large",
    githubUrl: "https://huggingface.co/spaces/DaniDaniels/stabilityai-stable-diffusion-3.5-large/tree/main",
    skills: [
      "Gradio Interface",
      "Python",
      "API Integration",
      "Hugging Face Spaces",
      "Stable Diffusion",
      "Image Generation",
      "Prompt Engineering",
      "Negative Prompt Handling"
    ]
  },
  {
    id: 5,
    title: "Mammography AI",
    subtitle: "Breast Cancer Classification System",
    youtubeId: "HJj4c_CaywI",
    videoUrl: "https://img.youtube.com/vi/HJj4c_CaywI/maxresdefault.jpg",
    description: "Deep learning system for automated breast cancer detection from mammograms using the Vindr-Mammo dataset, developed in association with NUST.",
    startDate: "5 May 2025",
    endDate: "10 May 2025",
    status: "Research",
    videoAvailable: true,
    technologies: ["TensorFlow/Keras", "EfficientNetB0", "Vision Transformer", "Gradio", "Streamlit", "DICOM", "OpenCV"],
    features: [
      { icon: HeartPulse, text: "92% AUC Score", color: "text-cyan-400" },
      { icon: BrainCircuit, text: "Multi-Model Architecture", color: "text-purple-400" },
      { icon: Stethoscope, text: "Clinical Integration", color: "text-green-400" },
      { icon: ScanEye, text: "DICOM Processing", color: "text-yellow-400" },
      { icon: Crosshair, text: "Ensemble Learning", color: "text-red-400" },
      { icon: Binary, text: "Class Imbalance Mitigation", color: "text-blue-400" },
      { icon: Network, text: "Model Interpretability", color: "text-orange-400" },
      { icon: FlaskConical, text: "Data Augmentation", color: "text-pink-400" },
    ],
    metrics: {
      users: "Medical Research",
      uptime: "100%",
      performance: 92,
      security: 99,
    },
    gradient: "from-pink-500 to-blue-600",
    associatedWith: "National University of Sciences and Technology (NUST)",
    keyAchievements: [
      "92% AUC score through ensemble techniques",
      "Reduced missed diagnoses in screening",
      "Clinical staff visualization interface",
      "Hospital system API integration"
    ],
    skills: [
      "TensorFlow/Keras",
      "Deep Learning",
      "Medical Image Analysis",
      "Computer Vision",
      "Transfer Learning",
      "Ensemble Methods",
      "Data Augmentation",
      "Model Deployment",
      "DICOM Processing",
      "Model Interpretability",
      "Clinical Workflow Integration"
    ],
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/MammographyAi/blob/main/Untitled6.ipynb",
    researchPaper: "https://arxiv.org/abs/example123"
  },
  {
    id: 10,
    title: "Research Agent",
    subtitle: "Research Agent using CrewAi and local LLm",
    description: "Senior Data Researcher that Uncover cutting-edge developments in the given topic.",
    startDate: "6 April 2025",
    endDate: "10 April 2025",
    status: "Research",
    videoAvailable: false,
    videoUrl: "/placeholder.svg?height=400&width=600",
    technologies: ["CrewAi", "python", "CrewAi-tools", "Local-llm", "ollama/llama3.2:1b"],
    features: [
      { icon: HeartPulse, text: "92% AUC Score", color: "text-cyan-400" },
      { icon: BrainCircuit, text: "Multi-Model Architecture", color: "text-purple-400" },
      { icon: Stethoscope, text: "Clinical Integration", color: "text-green-400" },
      { icon: ScanEye, text: "DICOM Processing", color: "text-yellow-400" },
      { icon: Crosshair, text: "Ensemble Learning", color: "text-red-400" },
      { icon: Binary, text: "Class Imbalance Mitigation", color: "text-blue-400" },
      { icon: Network, text: "Model Interpretability", color: "text-orange-400" },
      { icon: FlaskConical, text: "Data Augmentation", color: "text-pink-400" },
    ],
    metrics: {
      users: "Medical Research",
      uptime: "100%",
      performance: 92,
      security: 99,
    },
    gradient: "from-pink-500 to-blue-600",
    associatedWith: "National University of Sciences and Technology (NUST)",
    keyAchievements: [
      "92% AUC score through ensemble techniques",
      "Reduced missed diagnoses in screening",
      "Clinical staff visualization interface",
      "Hospital system API integration"
    ],
    skills: [
      "TensorFlow/Keras",
      "Deep Learning",
      "Medical Image Analysis",
      "Computer Vision",
      "Transfer Learning",
      "Ensemble Methods",
      "Data Augmentation",
      "Model Deployment",
      "DICOM Processing",
      "Model Interpretability",
      "Clinical Workflow Integration"
    ],
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/Research-Agent-CrewAi-and-Ollama-local-llm-",
    researchPaper: "https://arxiv.org/abs/example123"
  },
  {
    id: 6,
    title: "LLM Chatbot",
    subtitle: "Open-Source AI Assistant",
    description: "Conversational AI chatbot using Streamlit, integrated with Ollama's open-source LLM (LLaMA) for generating responses with real-time streaming.",
    startDate: "Oct 2024",
    endDate: "Oct 2024",
    status: "Demo",
    videoAvailable: false,
    videoUrl: "/placeholder.svg?height=400&width=600",
    technologies: ["Streamlit", "Ollama", "LLaMA", "LiteLLM", "Python", "GitHub"],
    features: [
      { icon: MessageSquare, text: "Conversational AI", color: "text-cyan-400" },
      { icon: Bot, text: "LLaMA Integration", color: "text-purple-400" },
      { icon: Server, text: "Local Hosting", color: "text-green-400" },
      { icon: Server, text: "Real-time Streaming", color: "text-yellow-400" },
      { icon: Globe, text: "User-friendly UI", color: "text-red-400" },
      { icon: Code2, text: "Open-Source", color: "text-blue-400" }
    ],
    metrics: {
      users: "Local Deployment",
      uptime: "100%",
      performance: 88,
      security: 95,
    },
    gradient: "from-indigo-500 to-violet-600",
    associatedWith: "National University of Sciences and Technology (NUST)",
    skills: [
      "Streamlit",
      "Chatbot Development",
      "LiteLLM",
      "Python",
      "GitHub",
      "User Interface Design",
      "Local Hosting",
      "LLM Integration",
      "Real-time Streaming"
    ],
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/llm-chatbot"
  },
  {
    id: 7,
    title: "RecipeApp",
    subtitle: "MealDB API Explorer",
    description: "React application that fetches and displays recipes from the MealDB API with responsive design and interactive features.",
    startDate: "1 Sep 2023",
    endDate: "2 Sep 2023",
    status: "Live",
    videoAvailable: true,
    videoUrl: "https://img.youtube.com/vi/placeholder/maxresdefault.jpg", // Needs actual thumbnail if available
    technologies: ["React.js", "MealDB API", "CSS3", "JavaScript", "HTML5"],
    features: [
      { icon: CookingPot, text: "API Integration", color: "text-cyan-400" },
      { icon: Utensils, text: "Recipe Search", color: "text-purple-400" },
      { icon: ListRestart, text: "State Management", color: "text-green-400" },
      { icon: Smartphone, text: "Responsive Design", color: "text-yellow-400" },
      { icon: Code2, text: "React Hooks", color: "text-red-400" },
      { icon: Globe, text: "Conditional Rendering", color: "text-blue-400" }
    ],
    metrics: {
      users: "500+",
      uptime: "99.8%",
      performance: 90,
      security: 85,
    },
    gradient: "from-amber-500 to-orange-600",
    skills: [
      "Conditional Rendering",
      "Passing Props",
      "React.js",
      "API Integration",
      "Responsive Design",
      "Event Handling",
      "Fetching Data",
      "State Management",
      "Effect Hook",
      "Component Lifecycle"
    ],
    liveUrl: "https://recipe-app-demo.vercel.app",
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/Recipe-App"
  },
  {
    id: 12,
    title: "Windows Video Player",
    subtitle: "Electron-based Video Player for Windows",
    description: "A video player application built with Electron for Windows, providing a seamless video playback experience with support for various video formats.",
    youtubeId: "O2ITK35U8AQ",
    videoUrl: "https://img.youtube.com/vi/O2ITK35U8AQ/maxresdefault.jpg",
    startDate: "Aug 2023",
    endDate: "Aug 2023",
    status: "Live",
    videoAvailable: true,
    technologies: ["Electron", "JavaScript", "HTML5", "CSS3", "Node.js"],
    features: [
      { icon: MonitorPlay, text: "Video Playback", color: "text-cyan-400" },
      { icon: Video, text: "Multiple Format Support", color: "text-purple-400" },
      { icon: Smartphone, text: "User-friendly Interface", color: "text-green-400" },
      { icon: Code2, text: "Custom Controls", color: "text-yellow-400" },
      { icon: Globe, text: "Cross-platform Compatibility", color: "text-red-400" }
    ],
    metrics: {
      users: "1000+",
      uptime: "99.9%",
      performance: 95,
      security: 90,
    },
    gradient: "from-blue-500 to-indigo-600",
    skills: [
      "Electron",
      "JavaScript",
      "Node.js",
      "Video Playback",
      "User Interface Design",
      "Cross-platform Development"
    ],
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/Windows-Video-Player-Electron"
  },
  {
    id: 13,
    title: "YouTube Video Transcription",
    subtitle: "Automated Transcription Tool",
    description: "A tool that automatically transcribes YouTube videos, providing accurate text transcripts for video content.",
    youtubeId: "Je_G8ahtRxw",
    videoUrl: "https://img.youtube.com/vi/Je_G8ahtRxw/maxresdefault.jpg",
    startDate: "Jul 2023",
    endDate: "Jul 2023",
    status: "Live",
    videoAvailable: true,
    technologies: ["Python", "YouTube API", "Speech Recognition", "Flask", "JavaScript"],
    features: [
      { icon: FileText, text: "Automated Transcription", color: "text-cyan-400" },
      { icon: Mic, text: "Accurate Text Conversion", color: "text-purple-400" },
      { icon: Globe, text: "YouTube API Integration", color: "text-green-400" },
      { icon: Code2, text: "User-friendly Interface", color: "text-yellow-400" },
      { icon: Shield, text: "Secure Data Handling", color: "text-red-400" }
    ],
    metrics: {
      users: "500+",
      uptime: "99.8%",
      performance: 92,
      security: 95,
    },
    gradient: "from-green-500 to-teal-600",
    skills: [
      "Python",
      "Speech Recognition",
      "YouTube API",
      "Flask",
      "JavaScript",
      "Data Handling"
    ],
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/YouTube-Video-Transcription"
  }
];
