import {
  Activity,
  Eye,
  Shield,
  Users,
  Globe,
  Cpu,
  Database,
  Zap,
  BarChart2,
  Target,
  Clock,
  TrendingUp,
  Award,
  Layers,
  GitBranch,
  Code2,
  HeartPulse,
  BrainCircuit,
  Stethoscope,
  ScanEye,
  Crosshair,
  Binary,
  Network,
  FlaskConical,
  Scan,
  Palette,
  Image,
  TestTube2,
  Pulse,
  MessageSquare,
  Bot,
  CpuChip,
  Server,
  CookingPot,
  Utensils,
  ListRestart,
  Smartphone
} from "lucide-react";

export const projects = [
  {
    id: 1,
    title: "Neon-Nexus",
    subtitle: "Real-time Auction Platform",
    description: "A revolutionary real-time auction platform powered by AI, featuring live bidding, intelligent product recommendations, and seamless payment integration.",
    youtubeId: "zuuFVVFkMno",
    videoUrl: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://neon-nexus-demo.vercel.app",
    githubUrl: "https://github.com/username/neon-nexus",
    startDate: "Jan 2024",
    endDate: "Present",
    status: "Live",
    videoAvailable: true,
    technologies: ["Next.js 15", "Supabase", "WebSockets", "Stripe", "Google Vision API", "Tailwind CSS"],
    features: [
      { icon: Activity, text: "Real-time bidding", color: "text-cyan-400" },
      { icon: Eye, text: "AI product analysis", color: "text-purple-400" },
      { icon: Shield, text: "Secure payments", color: "text-green-400" },
      { icon: Users, text: "1000+ concurrent users", color: "text-yellow-400" },
    ],
    metrics: {
      users: "1000+",
      uptime: "99.9%",
      performance: 98,
      security: 95,
    },
    gradient: "from-cyan-500 to-purple-600",
  },
  {
    id: 2,
    title: "Image-Gen",
    subtitle: "AI Image Generator App",
    description: "An AI Image Generator app using Next.js that leverages advanced technologies to bring AI-generated images to life.",
    youtubeId: "YRrcWkOyxPs",
    videoUrl: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://image-gen-demo.vercel.app",
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/Image-gen",
    startDate: "7/dec/2024",
    endDate: "12/dec/2024",
    status: "Live",
    videoAvailable: true,
    technologies: ["Next.js", "Tailwind CSS", "Supabase", "Cloudinary", "Hono", "Shadcn", "Turbopack"],
    features: [
      { icon: Globe, text: "Dynamic Header", color: "text-red-400" },
      { icon: Cpu, text: "Customizable Footer", color: "text-blue-400" },
      { icon: Database, text: "AI Image Generation", color: "text-green-400" },
      { icon: Users, text: "Theme Selection", color: "text-yellow-400" },
      { icon: Shield, text: "Dark Mode Toggle", color: "text-purple-400" },
      { icon: Eye, text: "Image Upload and Storage", color: "text-cyan-400" },
      { icon: Zap, text: "Supabase Indexing", color: "text-orange-400" },
      { icon: Activity, text: "Fallback Mechanism", color: "text-pink-400" },
    ],
    metrics: {
      users: "500+",
      uptime: "99.5%",
      performance: 92,
      security: 90,
    },
    gradient: "from-purple-500 to-pink-600",
  },
  {
    id: 3,
    title: "Multiple PDF Chat App",
    subtitle: "Interactive PDF Conversational Interface",
    description: "A Streamlit app that allows users to chat with multiple PDFs using LangChain and Google Generative AI (Gemini).",
    youtubeId: "HCHF8BneqV8",
    liveUrl: "https://pdf-chat-app-demo.vercel.app",
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/-Chat-with-multiple-pdf",
    startDate: "25/Nov/2024",
    endDate: "25/Nov/2024",
    status: "Live",
    videoAvailable: true,
    technologies: ["Streamlit", "PyPDF2", "LangChain", "Google Generative AI", "FAISS", "dotenv"],
    features: [
      { icon: Database, text: "Multiple PDF Support", color: "text-green-400" },
      { icon: Globe, text: "Smart Interaction", color: "text-red-400" },
      { icon: Zap, text: "Vector Search with FAISS", color: "text-orange-400" },
      { icon: Shield, text: "Generative AI Integration", color: "text-purple-400" },
    ],
    metrics: {
      users: "1500+",
      uptime: "99.7%",
      performance: 95,
      security: 93,
    },
    gradient: "from-blue-500 to-green-600",
  },
  {
    id: 4,
    title: "Cricket Runs And Win Predictor for Psl",
    subtitle: "Runs & Winner Prediction System trained on 278 Psl Matches",
    description: "Machine learning system to predict second-innings runs and match winners using historical cricket data, developed in association with NUST.",
    youtubeId: "FW8QQd1dQ5w",
    startDate: "Jan 2025",
    endDate: "Jan 2025",
    status: "Demo",
    videoAvailable: true,
    technologies: ["Python", "Pandas", "XGBoost", "Scikit-learn", "PyYAML", "GridSearchCV", "KFold"],
    features: [
      { icon: BarChart2, text: "Dual Prediction System", color: "text-cyan-400" },
      { icon: Target, text: "Run Rate Analysis", color: "text-purple-400" },
      { icon: Clock, text: "Balls Remaining Calculation", color: "text-green-400" },
      { icon: TrendingUp, text: "Feature Engineering", color: "text-yellow-400" },
      { icon: Award, text: "Model Optimization", color: "text-red-400" },
      { icon: Layers, text: "Pipeline Creation", color: "text-blue-400" },
      { icon: GitBranch, text: "Cross-Validation", color: "text-orange-400" },
      { icon: Code2, text: "Data Preprocessing", color: "text-pink-400" },
    ],
    metrics: {
      users: "NUST Research",
      uptime: "100%",
      performance: 96,
      security: 98,
    },
    gradient: "from-orange-500 to-red-600",
    associatedWith: "National University of Sciences and Technology (NUST)",
    keyAchievements: [
      "Accurate run predictions (e.g., predicted 180 total runs when 100 needed in 5 overs)",
      "Winner classification with high accuracy",
      "Feature engineering for cricket-specific metrics",
      "Hyperparameter tuning with GridSearchCV"
    ],
    skills: [
      "Machine Learning",
      "Standardization and Normalization",
      "Regression Analysis",
      "One-Hot Encoding",
      "Data Cleaning",
      "Feature Engineering",
      "Hyperparameter Tuning",
      "Pipeline Creation",
      "Classification Models"
    ]
  },
  {
    id: 8,
    title: "StabilityAI Stable Diffusion 3.5 Large",
    subtitle: "AI Image Generation App",
    description: "A Gradio-based AI image generator using StabilityAI's Stable Diffusion 3.5 Large model, deployed on Hugging Face Spaces.",
    startDate: "about 2 months ago",
    endDate: "about 2 months ago",
    status: "Live",
    videoAvailable: false,
    technologies: ["Gradio", "Python", "Hugging Face Spaces", "Stable Diffusion 3.5", "Fal.ai API"],
    features: [
      { icon: Image, text: "AI Image Generation", color: "text-cyan-400" },
      { icon: Palette, text: "Prompt Customization", color: "text-purple-400" },
      { icon: Shield, text: "Secure API Integration", color: "text-green-400" },
      { icon: Globe, text: "Hugging Face Deployment", color: "text-yellow-400" },
      { icon: Cpu, text: "Fast SDXL Model", color: "text-red-400" },
      { icon: Users, text: "User-friendly Interface", color: "text-blue-400" }
    ],
    metrics: {
      users: "Hugging Face Community",
      uptime: "99.8%",
      performance: 94,
      security: 90,
    },
    gradient: "from-violet-500 to-indigo-600",
    liveUrl: "https://huggingface.co/spaces/DaniDaniels/stabilityai-stable-diffusion-3.5-large",
    githubUrl: "https://huggingface.co/spaces/DaniDaniels/stabilityai-stable-diffusion-3.5-large/tree/main",
    skills: [
      "Gradio Interface",
      "Python",
      "API Integration",
      "Hugging Face Spaces",
      "Stable Diffusion",
      "Image Generation",
      "Prompt Engineering",
      "Negative Prompt Handling"
    ]
  },
  {
    id: 5,
    title: "Mammography AI",
    subtitle: "Breast Cancer Classification System",
    youtubeId: "HJj4c_CaywI",
    description: "Deep learning system for automated breast cancer detection from mammograms using the Vindr-Mammo dataset, developed in association with NUST.",
    startDate: "5 May 2025",
    endDate: "10 May 2025",
    status: "Research",
    videoAvailable: true,
    technologies: ["TensorFlow/Keras", "EfficientNetB0", "Vision Transformer", "Gradio", "Streamlit", "DICOM", "OpenCV"],
    features: [
      { icon: HeartPulse, text: "92% AUC Score", color: "text-cyan-400" },
      { icon: BrainCircuit, text: "Multi-Model Architecture", color: "text-purple-400" },
      { icon: Stethoscope, text: "Clinical Integration", color: "text-green-400" },
      { icon: ScanEye, text: "DICOM Processing", color: "text-yellow-400" },
      { icon: Crosshair, text: "Ensemble Learning", color: "text-red-400" },
      { icon: Binary, text: "Class Imbalance Mitigation", color: "text-blue-400" },
      { icon: Network, text: "Model Interpretability", color: "text-orange-400" },
      { icon: FlaskConical, text: "Data Augmentation", color: "text-pink-400" },
    ],
    metrics: {
      users: "Medical Research",
      uptime: "100%",
      performance: 92,
      security: 99,
    },
    gradient: "from-pink-500 to-blue-600",
    associatedWith: "National University of Sciences and Technology (NUST)",
    keyAchievements: [
      "92% AUC score through ensemble techniques",
      "Reduced missed diagnoses in screening",
      "Clinical staff visualization interface",
      "Hospital system API integration"
    ],
    skills: [
      "TensorFlow/Keras",
      "Deep Learning",
      "Medical Image Analysis",
      "Computer Vision",
      "Transfer Learning",
      "Ensemble Methods",
      "Data Augmentation",
      "Model Deployment",
      "DICOM Processing",
      "Model Interpretability",
      "Clinical Workflow Integration"
    ],
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/MammographyAi/blob/main/Untitled6.ipynb",
    researchPaper: "https://arxiv.org/abs/example123",
    VideoUrl: "/placeholder.svg?height=400&width=600"
  },
  {
    id: 10,
    title: "Research Agent",
    subtitle: "Research Agent using CrewAi and local LLm",
    description: "Senior Data Researcher that Uncover cutting-edge developments in the given topic.",
    startDate: "6 April 2025",
    endDate: "10 April 2025",
    status: "Research",
    videoAvailable: false,
    technologies: ["CrewAi", "python", "CrewAi-tools", "Local-llm", "ollama/llama3.2:1b"],
    features: [
      { icon: HeartPulse, text: "92% AUC Score", color: "text-cyan-400" },
      { icon: BrainCircuit, text: "Multi-Model Architecture", color: "text-purple-400" },
      { icon: Stethoscope, text: "Clinical Integration", color: "text-green-400" },
      { icon: ScanEye, text: "DICOM Processing", color: "text-yellow-400" },
      { icon: Crosshair, text: "Ensemble Learning", color: "text-red-400" },
      { icon: Binary, text: "Class Imbalance Mitigation", color: "text-blue-400" },
      { icon: Network, text: "Model Interpretability", color: "text-orange-400" },
      { icon: FlaskConical, text: "Data Augmentation", color: "text-pink-400" },
    ],
    metrics: {
      users: "Medical Research",
      uptime: "100%",
      performance: 92,
      security: 99,
    },
    gradient: "from-pink-500 to-blue-600",
    associatedWith: "National University of Sciences and Technology (NUST)",
    keyAchievements: [
      "92% AUC score through ensemble techniques",
      "Reduced missed diagnoses in screening",
      "Clinical staff visualization interface",
      "Hospital system API integration"
    ],
    skills: [
      "TensorFlow/Keras",
      "Deep Learning",
      "Medical Image Analysis",
      "Computer Vision",
      "Transfer Learning",
      "Ensemble Methods",
      "Data Augmentation",
      "Model Deployment",
      "DICOM Processing",
      "Model Interpretability",
      "Clinical Workflow Integration"
    ],
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/Research-Agent-CrewAi-and-Ollama-local-llm-",
    researchPaper: "https://arxiv.org/abs/example123"
  },
  {
    id: 6,
    title: "LLM Chatbot",
    subtitle: "Open-Source AI Assistant",
    description: "Conversational AI chatbot using Streamlit, integrated with Ollama's open-source LLM (LLaMA) for generating responses with real-time streaming.",
    startDate: "Oct 2024",
    endDate: "Oct 2024",
    status: "Demo",
    videoAvailable: false,
    technologies: ["Streamlit", "Ollama", "LLaMA", "LiteLLM", "Python", "GitHub"],
    features: [
      { icon: MessageSquare, text: "Conversational AI", color: "text-cyan-400" },
      { icon: Bot, text: "LLaMA Integration", color: "text-purple-400" },
      { icon: Server, text: "Local Hosting", color: "text-green-400" },
      { icon: Server, text: "Real-time Streaming", color: "text-yellow-400" },
      { icon: Globe, text: "User-friendly UI", color: "text-red-400" },
      { icon: Code2, text: "Open-Source", color: "text-blue-400" }
    ],
    metrics: {
      users: "Local Deployment",
      uptime: "100%",
      performance: 88,
      security: 95,
    },
    gradient: "from-indigo-500 to-violet-600",
    associatedWith: "National University of Sciences and Technology (NUST)",
    skills: [
      "Streamlit",
      "Chatbot Development",
      "LiteLLM",
      "Python",
      "GitHub",
      "User Interface Design",
      "Local Hosting",
      "LLM Integration",
      "Real-time Streaming"
    ],
    githubUrl: "https://github.com/username/llm-chatbot"
  },
  {
    id: 7,
    title: "RecipeApp",
    subtitle: "MealDB API Explorer",
    description: "React application that fetches and displays recipes from the MealDB API with responsive design and interactive features.",
    startDate: "1 Sep 2023",
    endDate: "2 Sep 2023",
    status: "Live",
    videoAvailable: true,
    technologies: ["React.js", "MealDB API", "CSS3", "JavaScript", "HTML5"],
    features: [
      { icon: CookingPot, text: "API Integration", color: "text-cyan-400" },
      { icon: Utensils, text: "Recipe Search", color: "text-purple-400" },
      { icon: ListRestart, text: "State Management", color: "text-green-400" },
      { icon: Smartphone, text: "Responsive Design", color: "text-yellow-400" },
      { icon: Code2, text: "React Hooks", color: "text-red-400" },
      { icon: Globe, text: "Conditional Rendering", color: "text-blue-400" }
    ],
    metrics: {
      users: "500+",
      uptime: "99.8%",
      performance: 90,
      security: 85,
    },
    gradient: "from-amber-500 to-orange-600",
    skills: [
      "Conditional Rendering",
      "Passing Props",
      "React.js",
      "API Integration",
      "Responsive Design",
      "Event Handling",
      "Fetching Data",
      "State Management",
      "Effect Hook",
      "Component Lifecycle"
    ],
    liveUrl: "https://recipe-app-demo.vercel.app",
    githubUrl: "https://github.com/Muhammad-Daniyal-Imtiaz/Recipe-App"
  }
];
